services:
  spese-front:
    build: 
      context: .
    restart: always
    command: npm run dev
    env_file:
      - .env.local
    volumes:
      - ./public:/app/public
      - ./src:/app/src
    network_mode: "host"